# Generated by Django 4.2.11 on 2024-08-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datos',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=35)),
                ('Apellido', models.TextField(max_length=35)),
                ('Edad', models.IntegerField()),
                ('Fecha_Nacimiento', models.DateField()),
            ],
        ),
    ]
